### ISSUE TITLE
Alias paths break export

### ISSUE THREAD

**Issue by arjunmehta** [tscanlin/next-blog#15]
From your boilerplate in [custom-post.md](https://github.com/tscanlin/next-blog/blob/master/content/custom-post.md):

```markdown
paths:
  - /custom-post
  - /custom-post-alias
  - /subpath/custom-post-alias
```
when running `npm run build:content` and then `npm run build:export` I get the following error:

```
> next-blog@3.2.0 export ~/next-blog
> next export && cp -R static/* out/

> using build directory: ~/next-blog/.next
  copying "static" directory
  copying "static build" directory
  launching 11 workers
[=== ] Exporting (1/7)
Error occurred prerendering page "/custom-post": TypeError: Cannot read property 'title' of undefined
    at Index (~/next-blog/.next/server/static/6zaBqk6zC6TNCE7-lIOZ9/pages/post.js:362:92)
    at d (~/next-blog/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:498)
    at Za (~/next-blog/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
    at a.b.render (~/next-blog/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)
    at a.b.read (~/next-blog/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
    at renderToString (~/next-blog/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
    at render (~/next-blog/node_modules/next/dist/next-server/server/render.js:81:16)
    at renderPage (~/next-blog/node_modules/next/dist/next-server/server/render.js:296:20)
    at ~/next-blog/.next/server/static/6zaBqk6zC6TNCE7-lIOZ9/pages/_document.js:600:17
    at Generator.next (<anonymous>)

Error occurred prerendering page "/custom-post-alias": TypeError: Cannot read property 'title' of undefined
    at Index (~/next-blog/.next/server/static/6zaBqk6zC6TNCE7-lIOZ9/pages/post.js:362:92)
    at d (~/next-blog/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:498)
    at Za (~/next-blog/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
    at a.b.render (~/next-blog/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)
    at a.b.read (~/next-blog/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
    at renderToString (~/next-blog/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
    at render (~/next-blog/node_modules/next/dist/next-server/server/render.js:81:16)
    at renderPage (~/next-blog/node_modules/next/dist/next-server/server/render.js:296:20)
    at ~/next-blog/.next/server/static/6zaBqk6zC6TNCE7-lIOZ9/pages/_document.js:600:17
    at Generator.next (<anonymous>)

Error occurred prerendering page "/subpath/custom-post-alias": TypeError: Cannot read property 'title' of undefined
    at Index (~/next-blog/.next/server/static/6zaBqk6zC6TNCE7-lIOZ9/pages/post.js:362:92)
    at d (~/next-blog/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:498)
    at Za (~/next-blog/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
    at a.b.render (~/next-blog/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)
    at a.b.read (~/next-blog/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
    at renderToString (~/next-blog/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
    at render (~/next-blog/node_modules/next/dist/next-server/server/render.js:81:16)
    at renderPage (~/next-blog/node_modules/next/dist/next-server/server/render.js:296:20)
    at ~/next-blog/.next/server/static/6zaBqk6zC6TNCE7-lIOZ9/pages/_document.js:600:17
    at Generator.next (<anonymous>)
Exporting (7/7)
Error: Export encountered errors
    at _default (~/next-blog/node_modules/next/dist/export/index.js:15:734)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR! code ELIFECYCLE
...
```

Removing  the alias paths from the custom-post seems to resolve the issue, albeit without alias paths of course.

**Comment by arjunmehta** [comment]
Actually a follow up, the above solution (removing the aliases) doesn't actually resolve the issue. It seems the `content/custom-post` doesn't seem to be getting built, though it does exist in `summary.json`

**Comment by tscanlin** [comment]
Can you link me to an example where I can reproduce this issue?

**Comment by arjunmehta** [comment]
It would be the master branch of this repo as of this particular moment, or the latest commit: https://github.com/tscanlin/next-blog/tree/149924108d1e5cb5b2a668ce80742579d29b9d22

I'm using Node 10.15.3. Steps to reproduce:

- `git clone git@github.com:tscanlin/next-blog.git && cd next-blog`
- `npm install`
- `npm run build:content`
- `npm start`
- Open browser to localhost:3000
- Navigate to "First post"
- Click on "another post" link

Error in browser:
```
×
TypeError: Cannot read property 'title' of undefined
Index
./pages/post.js:38
  35 |   }
  36 | `}</style>
  37 | <Page
> 38 |   siteTitle={`${CONFIG.siteTitle} - ${pageJson.title}`}
     | ^  39 |   heroTitle={CONFIG.siteTitle}
  40 |   description={CONFIG.description}
  41 |   stylesheets={CONFIG.stylesheets}
```

Error in console:
```
withRouter(Index) returned an empty object from `getInitialProps`. This de-optimizes and prevents automatic static optimization. https://err.sh/zeit/next.js/empty-object-getInitialProps
TypeError: Cannot read property 'title' of undefined
    at Index (~/Working/temp/next-blog/.next/server/static/development/pages/post.js:2240:92)
    at processChild (~/Working/temp/next-blog/node_modules/react-dom/cjs/react-dom-server.node.development.js:3206:14)
    at resolve (~/Working/temp/next-blog/node_modules/react-dom/cjs/react-dom-server.node.development.js:3126:5)
    at ReactDOMServerRenderer.render (~/Working/temp/next-blog/node_modules/react-dom/cjs/react-dom-server.node.development.js:3600:22)
    at ReactDOMServerRenderer.read (~/Working/temp/next-blog/node_modules/react-dom/cjs/react-dom-server.node.development.js:3538:29)
    at renderToString (~/Working/temp/next-blog/node_modules/react-dom/cjs/react-dom-server.node.development.js:4247:27)
    at render (~/Working/temp/next-blog/node_modules/next/dist/next-server/server/render.js:81:16)
    at Object.renderPage (~/Working/temp/next-blog/node_modules/next/dist/next-server/server/render.js:322:20)
    at ~/Working/temp/next-blog/.next/server/static/development/pages/_document.js:847:21
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (~/Working/temp/next-blog/.next/server/static/development/pages/_document.js:217:24)
    at _next (~/Working/temp/next-blog/.next/server/static/development/pages/_document.js:239:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

And of course running `npm run build:export` gives the error first mentioned.

**Comment by tscanlin** [comment]
I have a PR that should fix this. Please see #16 and let me know if that fixes the issue for you. It's working for me locally.

**Comment by tscanlin** [comment]
`3.2.1` is published with this fix. Thanks for reporting the issue!
