### ISSUE TITLE
Cannot find module './content/summary.json'

### ISSUE THREAD

**Issue by Kikobeats** [tscanlin/next-blog#6]
```
> next-blog@1.1.0 start /Users/josefranciscoverdugambin/Downloads/next-blog
> node server.js

atom .
Error: Cannot find module './content/summary.json'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/josefranciscoverdugambin/Downloads/next-blog/next.config.js:1:22)
    at Module._compile (module.js:649:30)
    at Module._compile (/Users/josefranciscoverdugambin/Downloads/next-blog/node_modules/source-map-support/source-map-support.js:483:25)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
```

**Comment by tscanlin** [comment]
can you try running `npm run build:content` first?
